imports:
    - { resource: tables.yml }

services:
    danieltj.memberreputation.listener:
        class: danieltj\memberreputation\event\listener
        arguments:
            - '@auth'
            - '@controller.helper'
            - '@template'
            - '@language'
            - '@user'
            - '@danieltj.memberreputation.core.functions'
            - '@path_helper'
        tags:
            - { name: event.listener }

    danieltj.memberreputation.like_post:
        class: danieltj\memberreputation\controller\like_post
        arguments:
            - '@auth'
            - '@request'
            - '@user'
            - '@notification_manager'
            - '@danieltj.memberreputation.core.functions'
            - '%core.php_ext%'

    danieltj.memberreputation.dislike_post:
        class: danieltj\memberreputation\controller\dislike_post
        arguments:
            - '@auth'
            - '@request'
            - '@user'
            - '@notification_manager'
            - '@danieltj.memberreputation.core.functions'
            - '%core.php_ext%'

    danieltj.memberreputation.core.functions:
        class: danieltj\memberreputation\core\functions
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@language'
            - '@request'
            - '@user'
            - '%core.table_prefix%'
            - '%core.root_path%'
            - '%core.php_ext%'

    danieltj.memberreputation.notification.type.like:
        class: danieltj\memberreputation\notification\type\like
        shared: false
        parent: notification.type.base
        calls:
            - [ set_controller_helper, [ '@controller.helper' ] ]
            - [ set_user_loader, [ '@user_loader' ] ]
        tags:
            - { name: notification.type }

    danieltj.memberreputation.notification.type.dislike:
        class: danieltj\memberreputation\notification\type\dislike
        shared: false
        parent: notification.type.base
        calls:
            - [ set_controller_helper, [ '@controller.helper' ] ]
            - [ set_user_loader, [ '@user_loader' ] ]
        tags:
            - { name: notification.type }
